module.exports = function () {
  return {
    "paths"              : {
      "appRoot"            : "site/",
      "bowerSrc"           : "bower_components",
      "bowerAssetsDest"    : "dist",
      "bowerStylesDest"    : "src/styles",
      "imgSrc"             : "src/images/**",
      "imgDest"            : "images",
      "fontSrc"            : "src/fonts/**/*",
      "fontDest"           : "fonts",
      "bodyScriptSrc"      : ["src/script/*.js"],
      "headScriptSrc"      : ["src/script/head/**/*.js"],
      "pageScriptSrc"      : ["src/script/page/**/*.js"],
      "scriptDest"         : "script",
      "stylesSrc"          : "src/styles/styles.scss",
      "stylesComponentsSrc": 'src/styles/components/',
      "stylesDest"         : "css",
      "scssLintConfig"     : "node_modules/scss-styleguide/.scss-lint.yml",
      "htdocs"             : "d:\\php\\",
    },
    "sassIncludePaths"   : [],
    "sassOutputStyle"    : "compressed",
    "bowerAssetFileTypes": "png,gif,svg,jpeg,jpg,woff,woff2,eot,ttf,otf",
    "bowerScriptFile"    : "bower.min.js",
    "bowerStylesFile"    : "_bower.scss",
    "headScriptFile"     : "headscripts.min.js",
    "scriptFile"         : "script.min.js",
  };
}
